<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../ServiceDefaults/KubeMQ.Aspire.Examples.ServiceDefaults.csproj" />
    <ProjectReference Include="../../../src/KubeMQ.Aspire.Client/KubeMQ.Aspire.Client.csproj" />
  </ItemGroup>
</Project>
